"""Add bot_response column

Revision ID: 69f3022e1d96
Revises: 
Create Date: 2025-02-03 09:54:18.848120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69f3022e1d96'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interactions', sa.Column('original_content', sa.String(length=280), nullable=True))
    op.add_column('interactions', sa.Column('bot_response', sa.String(length=280), nullable=True))
    op.drop_column('interactions', 'sentiment')
    op.drop_column('interactions', 'response')
    op.drop_column('interactions', 'content')
    op.drop_column('users', 'interaction_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('interaction_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('interactions', sa.Column('content', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('interactions', sa.Column('response', sa.VARCHAR(length=280), autoincrement=False, nullable=True))
    op.add_column('interactions', sa.Column('sentiment', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('interactions', 'bot_response')
    op.drop_column('interactions', 'original_content')
    # ### end Alembic commands ###
